### ISSUE TITLE
Add a check, if sudoku is solvable.

### ISSUE THREAD

**Issue by Michael36500** [MisansProducts/Sudoku-Board-Generator#6]
I was playing a bit with the program, and found quite a big issue. If you set some really high difficulty, than you can get unsolvable sudokus, for example this one with difficulty 95
![hidden_board](https://user-images.githubusercontent.com/104157791/177011708-602e4e7c-1260-47b3-983a-c51f46f31023.png)
I believe that I can do some kind of fix...

**Comment by MisansProducts** [comment]
Make sure you update your fork before creating a pull request. I have made commits to the project.

**Comment by Michael36500** [comment]
Oh no, I just realized, that all sudokos all solvable, even completely empty. So I am afraid that there isn't any possible fix...
Sorry, my bad

**Comment by MisansProducts** [comment]
> Oh no, I just realized, that all sudokos all solvable, even completely empty. So I am afraid that there isn't any possible fix... Sorry, my bad

Well, technically there **is** a solution, but without much information it is unsolvable. If you think that is fair for typing "99" as the difficulty then it is fine as it is.

**Comment by Michael36500** [comment]
> > Oh no, I just realized, that all sudokos all solvable, even completely empty. So I am afraid that there isn't any possible fix... Sorry, my bad
> 
> Well, technically there **is** a solution, but without much information it is unsolvable. If you think that is fair for typing "99" as the difficulty then it is fine as it is.

My problem was where to make line between teoratically solvable and practiclly solvable
